#+TITLE: Hugo Heagren
#+AUTHOR: Hugo Heagren
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: cv
# #+LATEX_HEADER: \usepackage{setspace}
# #+LATEX_HEADER: \setstretch{1.25}

* Contact Details
- [[mailto:hugo@heagren.com][hugo@heagren.com]]
- 07958997156
- SW8 (home) and WC2R (university)

* Previous roles
- 2016--2018 :: *Front of house staff, BooBooCoffee* (Big 7 third best
  coffee shop in the country). Greeted customers; took orders;
  delivered food and drinks; cleaned equipment; assisted with
  open/close; some experience of making coffee.
- 2018--2021 :: *Front of house University of Southampton bar and cafe*.
  Greeted customers; served drinks; coordinated with kitchen;
  experience preparing and serving alcoholic drinks.
- 2021--2022 :: online tutoring GCSE maths and English
- 2022 :: *Barista and Front of House, Cafe Aristo* Front of house;
  took orders; made drinks; managed stock and delivery tracking; open
  and close procedures; all-day solo shifts.

* Other experience
- from 2017 :: Volunteer staff for the [[https://www.fsc.org.uk/][Forest School Camps]]. Experience
  of working with a large team in difficult situations.
- from 2018 :: Keen sailor. I have my RYA Yachtmaster Coastal, sailed
  over 5,000 miles around Europe, have raced offshore with the [[https://www.rorc.org][RORC]]
  and [[https://jog.org.uk][JOG]]. Significant experience of stressful environments and work
  well under pressure (can make coffee at a 45° angle)

* Skills and qualities
- Engaging, enjoy working with people
- Experience working in cafes and coffee shops
- Work well in a large team
- Love coffee, food and wine
- Basic latte art (hearts, leaves, etc.)
